kind: pipeline
type: docker
name: hello-world

steps:
- name: configurations
  image: docker
  settings:
    repo: ravi0153/codebuffer
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest

- name: build-public
  image: docker:dind
  depends_on: [configurations]
  commands:
    - docker build -t mypublic:latest .