kind: pipeline
type: docker
name: build

server:
  host: https://3af6-2401-4900-1c5c-9e64-7efe-77bb-baa-aeba.ngrok-free.app/
  USER: ubuntu

trigger:
  branch:
    - dev-ravi
  event:
    - push
    - pull_request

steps:
  - name: build-public
    image: docker:19.03-dind
    environment:
      USERNAME: "$docker_username"
      PASSWORD: "$docker_password"
      TOKEN: "$drone_token"
      SERVER: "$drone_server"
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - cd public && pwd
      - dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - sleep 5  
      - docker build -t mypublic:latest .
      - docker tag mypublic:latest ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}
      - docker push ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}

  - name: build-server
    image: docker:19.03-dind
    environment:
      USERNAME: "$docker_username"
      PASSWORD: "$docker_password"
      TOKEN: "$drone_token"
      SERVER: "$drone_server"
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - export DRONE_SERVER="$SERVER"
      - export DRONE_TOKEN="$TOKEN"
      - cd server
      - docker build -t myserver:latest .
      - docker tag myserver:latest ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
      - docker push ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}