kind: pipeline
type: docker
name: build

server:
  host: https://3af6-2401-4900-1c5c-9e64-7efe-77bb-baa-aeba.ngrok-free.app/
  USER: ubuntu

trigger:
  branch:
    - dev-ravi
  event:
    - push
    - pull_request

steps:
  - name: build-public
    image: docker:19.03-dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: drone_token
      SERVER:
        from_secret: drone_server
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - cd public && pwd
      - docker run --privileged -d --name mypublic-dind -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/drone/src docker:dind
      - sleep 5  # Wait for Docker daemon to start
      - su -c "docker build -t mypublic:latest ."
      - su -c "docker tag mypublic:latest ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}"
      - su -c "docker push ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}"
      - su -c "docker image rm -f ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}"

  - name: build-server
    image: docker:19.03-dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: drone_token
      SERVER:
        from_secret: drone_server
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - export DRONE_SERVER=$SERVER
      - export DRONE_TOKEN=$TOKEN
      - cd server
      - docker build -t myserver:latest .
      - docker tag myserver:latest ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
      - docker push ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
      - docker image rm -f ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}