kind: pipeline
type: ssh
name: build

server:
  host: https://3af6-2401-4900-1c5c-9e64-7efe-77bb-baa-aeba.ngrok-free.app/
  user: ubuntu

trigger:
  branch:
    - dev-ravi
  event:
    - push
    - pull_request

  # - name: install-docker
  #   image: docker:dind
  #   commands:
  #     - echo "Docker is already available in the Docker-in-Docker environment."
steps:
  - name: build-public
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: drone_token
      SERVER:
        from_secret: drone_server
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - export DRONE_SERVER=$SERVER
      - export DRONE_TOKEN=$TOKEN
      - pwd
      - cd public
      - pwd
      - ls -la
      - sudo service start docker
      - sudo docker build -t mypublic:latest .
      - sudo docker tag mypublic:latest ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}
      - sudo docker push ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}
      - sudo docker image rm -f ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}

  - name: build-server
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: drone_token
      SERVER:
        from_secret: drone_server
    commands:
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - export DRONE_SERVER=$SERVER
      - export DRONE_TOKEN=$TOKEN
      - cd server
      - docker build -t myserver:latest .
      - docker tag myserver:latest ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
      - docker push ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
      - docker image rm -f ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}