kind: pipeline
name: default

trigger:
  branch:
    - dev-ravi
  event:
    - push
    - pull_request

steps:
- name: test
  image: docker:latest
  commands:
  - cd server/
  - docker build -t mypublic .