kind: pipeline
name: default

trigger:
  branch:
    - dev-ravi
  event:
    - push
    - pull_request

steps:
- name: test
  image: node
  commands:
  - cd server/Dockerfile # Change to the correct directory
  - npm install
  - npm test