kind: pipeline
type: ssh
name: build

server:
  host: https://3af6-2401-4900-1c5c-9e64-7efe-77bb-baa-aeba.ngrok-free.app/
  user: ubuntu

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: configurations
    depends_on: [clone]
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
      TOKEN:
        from_secret: drone_token
    commands:
      - sudo docker login -u $USERNAME -p $PASSWORD
      - export DRONE_SERVER=https://9ca8-2401-4900-1c5d-1394-e900-b348-f55c-f7b.ngrok-free.app 
      - export DRONE_TOKEN=$TOKEN

  - name: build-public
    depends_on: [configurations]
    commands:
      - cd public
      - sudo docker build -t mypublic:latest .
      - sudo docker tag mypublic:latest ravi0153/codebuffer:mypublic1.0
      - sudo docker push ravi0153/codebuffer:mypublic1.0
      - sudo docker image rm -f ravi0153/codebuffer:mypublic1.0

  - name: build-server
    depends_on: [configurations]
    commands:
      - cd server
      - sudo docker build -t myserver:latest .
      - sudo docker tag myserver:latest ravi0153/codebuffer:myserver1.0
      - sudo docker push ravi0153/codebuffer:myserver1.0
      - sudo docker image rm -f ravi0153/codebuffer:myserver1.0